### ISSUE TITLE
Unable to find 'omniverse-kit' package

### ISSUE THREAD

**Issue by qingdengxu** [fan-ziqi/IsaacLab#2]
![image](https://github.com/user-attachments/assets/f91e22fd-e23e-4e89-ab79-0e2c111c804a)

**Comment by fan-ziqi** [comment]
能否附带完整报错截图

**Comment by qingdengxu** [comment]
其他地方都没有报错，就在启动isaac sim 和isaac lab图形化界面的时候报错，  Unable to find 'omniverse-kit' package

**Comment by fan-ziqi** [comment]
那我就不知道了，没有完整log无法判断。
